### ISSUE TITLE
Optional / Nullable decorator or type helper

### ISSUE THREAD

**Issue by buschtoens** [ember-decorators/argument#35]
When using the `@type` decorator for field that don't necessarily need to be defined and don't have a default value, i.e. optional or "nullable" fields, it's a bit tedious to have to define a union just for that.

I suggest we add an `@optional` or `@nullable` decorator, that effectively wraps the specified type in a `unionOf(specifiedType, unefined, null)`.

This would allow the following code:

```js
import Component from '@ember/component';
import { argument } from '@ember-decorators/argument';
import { type, optional } from '@ember-decorators/argument/type';
import { immutable } from '@ember-decorators/argument/validation';

export default class ExampleComponent extends Component {
  @argument
  @optional
  @type('string')
  arg;
}
```

Alternatively `optional` or `nullable` could just be a [`helper`](https://github.com/ember-decorators/argument/tree/eafb722d54f3189c3fe31b5da0cc44909d4a49e6/addon/-debug/helpers):

```js
import Component from '@ember/component';
import { argument } from '@ember-decorators/argument';
import { type, optional } from '@ember-decorators/argument/type';
import { immutable } from '@ember-decorators/argument/validation';

export default class ExampleComponent extends Component {
  @argument
  @type(optional('string'))
  arg;
}
```

**Comment by pzuraq** [comment]
Yeah, I agree that optional syntax is pretty cumbersome here. It also makes the `@required` decorator kind of redundant if you use `@type` 😛

I'm leaning towards it being a type helper, since that'd be much more straightforward to implement and apply universally. If it were a decorator, I would expect it to operate much like `@required`, only running the validation on component initialization, whereas a type helper would I think create a union type that applies at all times (whenever the field is set, or new properties are passed in, etc)

**Comment by buschtoens** [comment]
Awesome-sauce. Makes total sense. I'll fix up a PR tomorrow.
