### ISSUE TITLE
Update to be a pure validation library, add TS support

### ISSUE THREAD

**Issue by pzuraq** [ember-decorators/argument#83]
Now that RFC 337 has been merged and we are about ready to release it, the runtime functionality for this library will become _mostly_ obsolete. There is still some usefulness in the `defaultIfUndefined` functionality for default values on props, but I think this is something that should be solved separately. 

This library can become a thin validation library that has _all_ of its code stripped in production builds. This would make it a more attractive choice for addon authors and maintainers in general, since it would provide safety to even non-TS users that their components are being used correctly.

## API Changes

The API can be simplified since `@argument` won't have any options, currently. It may make sense to remove `@type`, `@immutable`, and `@required` in favor of a single argument decorator:

```js
@required @argument @type('string');

// same as
@argument('string');
```

In addition we should think of a way forward with Sparkles/Glimmer components, since they will have their args provided on a hash. We may also be able to leverage Typescript by using a transform to grab type information for the decorators, if it exists.

**Comment by alexlafroscia** [comment]
I'd like to take this on, with the following proposal:

- Create an `argument` package in the existing mono-repo (in part as a means to have a clean slate to work off of)
- Target only Babel 7
- Target only the stage 2 decorators proposal
- Ship with the example API shown above, plus a single `type` file where you can import the validator helpers like `optional`, `shapeOf` etc. and the type aliases such as `ClosureAction`
  - Note: having used `argument` extensively in my own code, I find the fact that those are in two different files pretty painful. There's a lot more clutter than there needs to be.

**Comment by pzuraq** [comment]
I’m not really comfortable moving this package into the monorepo just yet. Currently, the monorepo represents to bare minimum of packages needed to have feature-parity with vanilla Ember. With the decorators RFC, it may need to split into two logical groups, the polyfill group and the legacy support group. This would be a third group, additional decorators libraries, not part of the core programming model.

**Comment by pzuraq** [comment]
Totally on board with everything else though 😄

**Comment by alexlafroscia** [comment]
Alright, no problem! I'll just do my work in the original repo then.

**Comment by alexlafroscia** [comment]
@pzuraq what do you think about keeping the validation around providing arguments that are not defined with `@argument` on a component?

Should that still throw an error?

I think, personally, that it's pretty helpful to get that quick validation that something is missing.

**Comment by pzuraq** [comment]
Absolutely think this should still throw, I think this is one of the more valuable parts of this library as well 👍

**Comment by alexlafroscia** [comment]
Great, I'll make sure that that still works.

What do you think about the minimum supported Ember version? I have conflicting feelings.

On the one hand, I don't like dropping support for older Ember versions, only because we, as a community, try hard to bring people on older versions along as far as we can.

On the other, `3.6` ([or `3.4`, with your polyfill](https://www.npmjs.com/package/ember-native-class-polyfill)) changes the `constructor`/`init` behavior and removes a significant piece of this addon's behavior, because the framework "just works that way" now. The code is cleaner and easier if we can assume that `3.4` is the minimum version we're supporting, and folks on an earlier version of Ember can continue using the existing `@argument` version. Because using classes and decorators is kind of an "edge" Ember use case right now, fraught with warnings that thing might break, I feel a lot less bad than I normally would dropping older Ember version support, and am personally on the mindset that `3.4` is a good minimum target. Going back further would be done as the polyfill supports older versions too, if that ever happens.

What do you think about the minimum version?

**Comment by alexlafroscia** [comment]
One of the cool things about trying to lean more on the ES6 class behavior is that we can remove a lot of the implicit mixin injection in favor of things that "just work" with the Stage 2 decorator spec. So far I've been able to remove the validation-logic mixin, which was injected implicitly into all `EmberObject`s, with explicitly injecting it only when `@argument` is used. Yay for less side-effects!

**Comment by pzuraq** [comment]
I think we should only support v3.6+ behavior, along with any versions which are supported by the polyfill. It's too much work to try to support the older behavior, and it can lead to weird behaviors and issues when updating Ember versions. Like you said, this has definitely been beta-ish territory for a long time, and there hasn't been _that_ much early adoption (and we're helping the early adopters as much as possible when they need help).

We can point users with earlier Ember versions to the `v0.8` version series of this library if they need support still as well.
