### ISSUE TITLE
object.js:20 Uncaught TypeError: Cannot convert undefined or null to object at Function.getOwnPropertyDescriptor

### ISSUE THREAD

**Issue by artemgurzhii** [ember-decorators/argument#98]
**Versions:** 
 - `ember` -> `3.4.8`
 - `ember-data` -> `3.4.4`
 - `ember-decorators/argument` -> `1.0.0-beta.2`
 - `ember-decorators/babel-transforms` -> `^3.1.0`
 - `ember-decorators` -> `^5.1.2`

**Error Message:**
 - `object.js:20 Uncaught TypeError: Cannot convert undefined or null to object at Function.getOwnPropertyDescriptor (<anonymous>)`

Error being thrown from the [addon/-private/utils/object.js#L9-L16](https://github.com/ember-decorators/argument/blob/master/addon/-private/utils/object.js#L9-L16)
[Here is an image](https://monosnap.com/file/ktNB8IVufsrJoolpUCWnxwpSw19v0f)

I'm having simple component with optional arguments

```hbs
// component.hbs
<ComponentName />  {{!-- This throws error --}}

<ComponentName
  @someProp={{"some string"}}
/>  {{!-- This does not --}}
```

```js
// component.js
import Component from '@ember/component';
import { argument } from '@ember-decorators/argument';
import { optional } from '@ember-decorators/argument/types';

export default class ComponentNameComponent extends Component {
  @argument(optional('string')) someProp;
}
```

**Comment by willviles** [comment]
I'm experiencing this too whilst trying to upgrade from `0.5.0`.

**Comment by alexlafroscia** [comment]
Sorry to hear there's been some issues upgrading -- thanks for checking out the beta version!

I upgraded out app at work recently and haven't run into this issue yet... I'm really curious what's different here. I guess I need to check that `target` is neither `undefined` _or_` null`, since we pretty explicitly ensure that `target` is not `undefined` before passing it to `getOwnPropertyDescriptors`

Is there any chance you can set your debugger in Chrome (or whatever) to pause on uncaught errors, trigger the problem, and check that `target` is in fact `null` when the exception is thrown? That would make me feel quite a bit more confident in adding that additional check as the solution.

**Comment by artemgurzhii** [comment]
@alexlafroscia `target` is not null or undefined at first run, but method `getPropertyDescriptor` calls itself recursively

**Comment by alexlafroscia** [comment]
Interesting... I'll try to reproduce in a new Ember app with the dependencies that you've mentioned.

If you have a reproduction you can point me to, that would really speed things along!
